/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controlador.Controlador;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static jdk.nashorn.tools.ShellFunctions.input;

/**
 *
 * @author luciano_simeao
 */
public class OpcaoFrame extends javax.swing.JFrame {

    /**
     * Creates new form opcaoFrame
     */
    public OpcaoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        botaoCarregarArquivo = new javax.swing.JButton();
        botaoCodificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCarregarArquivo.setText("Carregar Arquivo");
        botaoCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarregarArquivoActionPerformed(evt);
            }
        });

        botaoCodificar.setText("Codificar");
        botaoCodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCodificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bem-vindo ao Compilador Simpletron ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione uma opção:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoCarregarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(botaoCodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(botaoCarregarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botaoCodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarregarArquivoActionPerformed
        JFileChooser abrindoArquivo = new JFileChooser();
        String conteudo="";
        int resultado = abrindoArquivo.showOpenDialog(this);
        if(!(resultado == JFileChooser.CANCEL_OPTION)){
            File fileName = abrindoArquivo.getSelectedFile();
            FileReader input=null;
            try {
                input = new FileReader(fileName);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(OpcaoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedReader bufRead = new BufferedReader(input);
            String linha=null;
            try {
                linha = bufRead.readLine();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro na leitura do arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            try {
                linha = bufRead.readLine();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro na leitura do arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);    
            }
            conteudo = linha+"\n";
            while (linha != null){
                try {
                    linha = bufRead.readLine();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Erro na leitura do arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                if(linha != null)conteudo += linha+"\n";
            }
            CompiladorIO telaCompilador = new CompiladorIO(conteudo);
            telaCompilador.setVisible(true);
        }
        
//        String fileName=JOptionPane.showInputDialog("Insira o nome do arquivo (sem extensão)",
//                DISPOSE_ON_CLOSE)+".txt";
//        String path = "src/filesSimple/";
//        File diretorio = new File(path);
//	String arquivoContent = "";
//        File[] listFiles = diretorio.listFiles(new FileFilter() {
//            public boolean accept(File pathname) {
//		return pathname.getName().startsWith(fileName.substring(0,1)); // apenas arquivos que começam com a letra "a"
//            }
//        });
//
//        BufferedReader br = null;
//        try {
//            br = new BufferedReader(new FileReader(path+fileName));
//        } catch (FileNotFoundException ex) {
//            JOptionPane.showMessageDialog(rootPane, "Arquivo não encontrado!",
//                    "Erro", JOptionPane.ERROR_MESSAGE);
//        }
//        try {
//            if(br != null){
//                while(br.ready()){
//                    String linha = br.readLine();
//                    arquivoContent += linha;
//                    arquivoContent += "\n";
//                }
//            }
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(rootPane, "Erro na leitura do arquivo",
//                    "Erro", JOptionPane.ERROR_MESSAGE);
//        }
//        try {
//            br.close();
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(rootPane, "Erro no fechamento do arquivo",
//                    "Erro", JOptionPane.ERROR_MESSAGE);
//        }
//        System.out.println(arquivoContent);
//        CompiladorIO telaCompilador = new CompiladorIO(conteudo);
//        telaCompilador.setVisible(true);
    }//GEN-LAST:event_botaoCarregarArquivoActionPerformed

    
    private void botaoCodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCodificarActionPerformed
        CompiladorIO telaCompilador = new CompiladorIO("");
        telaCompilador.setVisible(true);
    }//GEN-LAST:event_botaoCodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opcaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opcaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opcaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opcaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcaoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCarregarArquivo;
    private javax.swing.JButton botaoCodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
